spring.application.name=eazybankbackend
spring.security.user.name=${SECURITY_USERNAME:banguela}
spring.security.user.password=${SECURITY_PASSWORD:guelito}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
